[platformio]
src_dir = src
include_dir = include

[env:esp32-s3-devkitc-1]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool
build_flags =
  -D CORE_DEBUG_LEVEL=3
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
lib_deps =
  https://github.com/ZinggJM/GxEPD2.git#1.6.9
  adafruit/Adafruit GFX Library@^1.11.11

